### ISSUE TITLE
Добавить минимальный фронтенд

### ISSUE THREAD

**Issue by FunFunFine** [romutchio/docs.github.io#7]
- Добавить страницу поиска, входа и просмотра
- Добавить  карусель сканов
- Реализовать шифрование и пароли

**Comment by OptimumDev** [comment]
Макет сайта
<img width="831" alt="Снимок экрана 2020-10-15 в 19 41 27" src="https://user-images.githubusercontent.com/38810090/96145255-774e7c80-0f1e-11eb-8c94-4d784e70b474.png">

**Comment by OptimumDev** [comment]
Главная страница при отсутствии пароля для шифрования **( 1 )**
<img width="617" alt="Снимок экрана 2020-10-15 в 19 40 12" src="https://user-images.githubusercontent.com/38810090/96145412-9c42ef80-0f1e-11eb-92d3-e64952b22a5a.png">

**Comment by OptimumDev** [comment]
Главная страница при наличии пароля для шифрования ( 2 )
<img width="621" alt="Снимок экрана 2020-10-15 в 19 40 22" src="https://user-images.githubusercontent.com/38810090/96145514-b8469100-0f1e-11eb-958c-0b62defda695.png">

**Comment by OptimumDev** [comment]
Диалоговое окно о сбросе пароля для шифрования (пароль скрыт) **( 3 )** [При нажатии на замок из состояния 2]
<img width="620" alt="Снимок экрана 2020-10-15 в 19 40 35" src="https://user-images.githubusercontent.com/38810090/96145561-c72d4380-0f1e-11eb-95e8-59f796821d7a.png">

**Comment by OptimumDev** [comment]
Диалоговое окно о сбросе пароля для шифрования (пароль показан) **( 4 )**
<img width="619" alt="Снимок экрана 2020-10-15 в 19 40 41" src="https://user-images.githubusercontent.com/38810090/96145674-e4621200-0f1e-11eb-9fa3-9a5b886aa609.png">

**Comment by OptimumDev** [comment]
Диалоговое окно при выборе документа (пароль есть) **( 5 )** [При нажатии на документ из состояния 2]
<img width="620" alt="Снимок экрана 2020-10-15 в 19 40 48" src="https://user-images.githubusercontent.com/38810090/96145730-f2b02e00-0f1e-11eb-8d0e-5d82db755016.png">

**Comment by OptimumDev** [comment]
Диалоговое окно при выборе документа (пароля нет) **( 6 )** [При нажатии на документ из состояния 1]
<img width="621" alt="Снимок экрана 2020-10-15 в 19 47 00" src="https://user-images.githubusercontent.com/38810090/96146005-3dca4100-0f1f-11eb-930b-938c0873eb09.png">

**Comment by OptimumDev** [comment]
Подтверждение при удалении **( 7 )** [При нажатии на "удалить" из состояний 5 и 6]
<img width="620" alt="Снимок экрана 2020-10-15 в 19 40 55" src="https://user-images.githubusercontent.com/38810090/96146115-63efe100-0f1f-11eb-8e11-6a98090e7411.png">

**Comment by OptimumDev** [comment]
Загрузка нового документа / редактирование (не готово к сохранению - нет названия и файла) **( 8 )** [При нажатии на "изменить" из состояний 5 и 6 / при нажатии на плюс из состояния 2]
<img width="620" alt="Снимок экрана 2020-10-15 в 19 41 02" src="https://user-images.githubusercontent.com/38810090/96146215-7ec25580-0f1f-11eb-9db8-20c56fa020e4.png">

**Comment by OptimumDev** [comment]
Загрузка нового документа / редактирование (готово к сохранению) **( 9 )**
<img width="619" alt="Снимок экрана 2020-10-15 в 19 41 08" src="https://user-images.githubusercontent.com/38810090/96146280-8f72cb80-0f1f-11eb-9cb9-448079f0f728.png">
